//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShoppingCartAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner Master.
        /// </summary>
        public static string BannerMaster {
            get {
                return ResourceManager.GetString("BannerMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Master.
        /// </summary>
        public static string BrandMaster {
            get {
                return ResourceManager.GetString("BrandMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Order Detail.
        /// </summary>
        public static string CancelOrderDetail {
            get {
                return ResourceManager.GetString("CancelOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Master.
        /// </summary>
        public static string CategoryMaster {
            get {
                return ResourceManager.GetString("CategoryMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Detail.
        /// </summary>
        public static string CustomerDetail {
            get {
                return ResourceManager.GetString("CustomerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Detail.
        /// </summary>
        public static string CustomerDetailMaster {
            get {
                return ResourceManager.GetString("CustomerDetailMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch Order Detail.
        /// </summary>
        public static string DispatchOrderDetail {
            get {
                return ResourceManager.GetString("DispatchOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Department.
        /// </summary>
        public static string NewDepartment {
            get {
                return ResourceManager.GetString("NewDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News and Seminar Master.
        /// </summary>
        public static string NewsAndSeminarMaster {
            get {
                return ResourceManager.GetString("NewsAndSeminarMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Image.
        /// </summary>
        public static string OfferImageMaster {
            get {
                return ResourceManager.GetString("OfferImageMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Detail.
        /// </summary>
        public static string OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Order Detail.
        /// </summary>
        public static string PendingOrderDetail {
            get {
                return ResourceManager.GetString("PendingOrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductImageMaster.
        /// </summary>
        public static string ProductImageMaster {
            get {
                return ResourceManager.GetString("ProductImageMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string ProductMaster {
            get {
                return ResourceManager.GetString("ProductMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set User Permission.
        /// </summary>
        public static string SetUserPermission {
            get {
                return ResourceManager.GetString("SetUserPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Master.
        /// </summary>
        public static string StateMaster {
            get {
                return ResourceManager.GetString("StateMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Category Master.
        /// </summary>
        public static string SubCategoryMaster {
            get {
                return ResourceManager.GetString("SubCategoryMaster", resourceCulture);
            }
        }
    }
}
